"""002_add_discussion_tables

Revision ID: 071e33dbd300
Revises: c14e79c27c2f
Create Date: 2026-09-26 04:05:33.095336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071e33dbd300'
down_revision: Union[str, None] = 'c14e79c27c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tag', sa.String(length=30), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('downvotes', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['discussion_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discussion_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_posts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_posts_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_posts_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_posts_topic'), ['topic'], unique=False)

    op.create_table('discussion_votes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['discussion_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discussion_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_votes_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_votes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_votes_user_id'))
        batch_op.drop_index(batch_op.f('ix_discussion_votes_post_id'))

    op.drop_table('discussion_votes')
    with op.batch_alter_table('discussion_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_posts_topic'))
        batch_op.drop_index(batch_op.f('ix_discussion_posts_scope'))
        batch_op.drop_index(batch_op.f('ix_discussion_posts_parent_id'))
        batch_op.drop_index(batch_op.f('ix_discussion_posts_author_id'))

    op.drop_table('discussion_posts')
    # ### end Alembic commands ###
